### ISSUE TITLE
First Release Error

### ISSUE THREAD

**Issue by patrickleet** [jaywcjlove/changelog-generator#100]
When add this action to a repo that has no releases yet, it throws an error.

Maybe it should just generate and empty changelog? Or a message "First release".

I am using this as a workaround to conditionally run the step only if previous tags exist via `if: env.previous_tag`:

```
    - name: previous tag
      run: |
        # set previous_tag to the last tag in the repo
        # or if the command throws an error, set it to nothing
        previous_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
        echo "previous_tag=$previous_tag" >> $GITHUB_ENV

    - name: Generate changelog
      id: changelog
      if: env.previous_tag
      uses: jaywcjlove/changelog-generator@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
```
