### ISSUE TITLE
Suggest some feature

### ISSUE THREAD

**Issue by vacnex** [jaywcjlove/changelog-generator#111]
Hi, thank for great work, I highly appreciate the convenience provided by this tool and I would like to contribute some ideas to further enhance its functionality.

1. Currently, the changelog is listed from top to bottom in chronological order, starting from the oldest to the newest. I want to categorize them into separate types. For example, feat will be listed under #Feature, fix will be under #Bugs, and so on for other types.

2. Sometimes, there are commits that I don't want to appear in the changelog, so I have used the following filter:
`^(?!type\b|feat\b|style\b|chore\b|doc\b|docs\b|build\b|fix\b|test\b|refactor\b|website\b|revert\ b|clean\b|perf\b|ci\b).*`
Therefore, I think there should be an option to allow users to create a custom type and include or exclude it from the changelog.

3. Some my projects are developed solely by me, there should also be an option to hide the author, as all commits are mine. I don't find it necessary to display @author on every entry in the changelog.

**Comment by jaywcjlove** [comment]
@vacnex To filter username display you can use `filter-author`

https://github.com/jaywcjlove/changelog-generator/blob/84887743aee3b665c86c3753ee12de534ce7b77a/action.yml#L13-L16

**Comment by jaywcjlove** [comment]
@vacnex `1`  idea, I may need to define templates to achieve this idea.

```yml
- name: Generate changelog
  uses: jaywcjlove/changelog-generator@main
  with:
    token: ${{ secrets.GITHUB_TOKEN }}
    filter-author: (jaywcjlove|小弟调调™|dependabot|renovate\\[bot\\]|dependabot\\[bot\\]|Renovate Bot)
    filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'
    template: |
        ## Bugs

        {{fix}}

        ## Feature

        {{feat}}{{type}}

        ## Document 

        {{doc}}
```

@vacnex If you are sure that your idea can be satisfied, I will start to realize it.
