### ISSUE TITLE
Add input to define project path (suggestion)

### ISSUE THREAD

**Issue by MarcosRava** [jaywcjlove/changelog-generator#96]
To enable the use in monorepo projects, I would like to be able to create different changelogs based on project path commits

Suggestion:
```
- name: Generate changelog
    id: changelog
    uses: jaywcjlove/changelog-generator@main
    with:
      token: ${{ secrets.GITHUB_TOKEN }}
      path: ./apps/my-aplication
    continue-on-error: true
```
